### PR TITLE
manage customer cert

### PR DESCRIPTION
**Pull request by skeeey**
Signed-off-by: liuwei <liuweixa@redhat.com>

### CODE REVIEW

**Comment by xuezhaojun** [comment]
Do we consider "copy and paste" or "make certrotation a helper repo" instead of "import certrotation from registration-operator"?
Since it seems registration-operator is not designed for this function.

**Comment by skeeey** [comment]
It's better to have common library to handle this, but it seems that it's not so bad to import the operator code, I don't think copy/paste is a good choice, or we create a library to handle this, and we may also include other common functions to this library, @qiujian16 what's your opinion?

**Comment by xuezhaojun** [comment]
/lgtm
We may separate this part into another repo in the future? 
I think for now import it in this way is ok. And We can continue other work based on this.

**Pull request merged**
